apiVersion: v2
name: argocd
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: argo-cd
    version: 9.4.1
    repository: https://argoproj.github.io/argo-helm
