apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  replicas: {{ .Values.replicaCount }}
  defaultUser:
    secretName: rabbitmq-custom-user
  service:
    type: ClusterIP
  persistence:
    storage: {{ .Values.storage }}
