apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-default-user
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: test
  password: test
  default_user.conf: |
    default_user = test
    default_pass = test
